-- Οργανωτής Βαφέα Pro - Reset & Import Database
-- Δημιουργήθηκε αυτόματα: 2025-11-12 19:28:15

SET FOREIGN_KEY_CHECKS = 0;
SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

-- ΔΙΑΓΡΑΦΗ ΔΕΔΟΜΕΝΩΝ
DELETE FROM `timesheets`;
ALTER TABLE `timesheets` AUTO_INCREMENT = 1;
DELETE FROM `job_workers`;
ALTER TABLE `job_workers` AUTO_INCREMENT = 1;
DELETE FROM `job_materials`;
ALTER TABLE `job_materials` AUTO_INCREMENT = 1;
DELETE FROM `invoices`;
ALTER TABLE `invoices` AUTO_INCREMENT = 1;
DELETE FROM `offers`;
ALTER TABLE `offers` AUTO_INCREMENT = 1;
DELETE FROM `calendar_events`;
ALTER TABLE `calendar_events` AUTO_INCREMENT = 1;
DELETE FROM `jobs`;
ALTER TABLE `jobs` AUTO_INCREMENT = 1;
DELETE FROM `workers`;
ALTER TABLE `workers` AUTO_INCREMENT = 1;
DELETE FROM `materials`;
ALTER TABLE `materials` AUTO_INCREMENT = 1;
DELETE FROM `clients`;
ALTER TABLE `clients` AUTO_INCREMENT = 1;
DELETE FROM `templates`;
ALTER TABLE `templates` AUTO_INCREMENT = 1;
DELETE FROM `settings`;
ALTER TABLE `settings` AUTO_INCREMENT = 1;

-- CLIENTS
INSERT INTO clients (name, phone, email, address, city, postal_code, afm, notes) VALUES ('Γιάννης Παπαδόπουλος', '6944123456', 'giannis@example.com', 'Δημοκρατίας 45', 'Αλεξανδρούπολη', '68100', '123456789', 'Τακτικός πελάτης - Προτιμά πρωινές ώρες');
INSERT INTO clients (name, phone, email, address, city, postal_code, afm, notes) VALUES ('Μαρία Νικολάου', '6955234567', 'maria@example.com', '14ης Μαΐου 15', 'Αλεξανδρούπολη', '68100', '987654321', 'Προτιμά ανοιχτά χρώματα, έχει αλλεργία σε έντονες μυρωδιές');
INSERT INTO clients (name, phone, email, address, city, postal_code, afm, notes) VALUES ('Κώστας Γεωργίου', '6976345678', 'kostas@example.com', 'Κύπρου 42', 'Αλεξανδρούπολη', '68100', '456789123', 'Επιχειρηματίας - Διαθέσιμος μετά τις 6μμ');
INSERT INTO clients (name, phone, email, address, city, postal_code, afm, notes) VALUES ('Ελένη Αθανασίου', '6987456789', 'eleni@example.com', 'Βενιζέλου 18', 'Αλεξανδρούπολη', '68100', '321654987', 'VIP πελάτης - Απαιτητική, προσοχή στη λεπτομέρεια');
INSERT INTO clients (name, phone, email, address, city, postal_code, afm, notes) VALUES ('Νίκος Δημητρίου', '6912567890', 'nikos@example.com', 'Καραολή και Δημητρίου 33', 'Αλεξανδρούπολη', '68100', '147258369', 'Νέος πελάτης');
INSERT INTO clients (name, phone, email, address, city, postal_code, afm, notes) VALUES ('Σοφία Παναγιώτου', '6923678901', 'sofia@example.com', 'Ελευθερίας 77', 'Αλεξανδρούπολη', '68100', '258369147', 'Ζητά πάντα προσφορά πρώτα');
INSERT INTO clients (name, phone, email, address, city, postal_code, afm, notes) VALUES ('Athanasios Zisoglou', '6978799299', 'zisoglou@hotmail.gr', 'Αγίου Δημητρίου 9', 'Αλεξανδρούπολη', '68100', '099876543', 'Ιδιοκτήτης - Test Account');
INSERT INTO clients (name, phone, email, address, city, postal_code, afm, notes) VALUES ('Ανδρέας Παύλου', '6934567890', 'andreas@example.com', 'Καποδιστρίου 22', 'Αλεξανδρούπολη', '68100', '741852963', 'Έχει κατάστημα καφέ');
INSERT INTO clients (name, phone, email, address, city, postal_code, afm, notes) VALUES ('Μαρίνα Χρήστου', '6945678901', 'marina@example.com', 'Ορφέως 5', 'Αλεξανδρούπολη', '68100', '852963741', 'Ζητά οικολογικά χρώματα');
INSERT INTO clients (name, phone, email, address, city, postal_code, afm, notes) VALUES ('Θανάσης Ιωάννου', '6956789012', 'thanasis@example.com', 'Σωκράτους 12', 'Αλεξανδρούπολη', '68100', '963741852', 'Νέος πελάτης');

-- WORKERS
INSERT INTO workers (name, phone, specialty, hourly_rate, daily_rate, status, hire_date, notes, total_hours, total_earnings) VALUES ('Δημήτρης Βασιλείου', '6923111222', 'Βαφέας Senior', 15.00, 100.00, 'active', '2024-01-15', 'Έμπειρος βαφέας με 10 χρόνια εμπειρία', 320.50, 4807.50);
INSERT INTO workers (name, phone, specialty, hourly_rate, daily_rate, status, hire_date, notes, total_hours, total_earnings) VALUES ('Γιώργος Αντωνίου', '6934222333', 'Ελαιοχρωματιστής', 12.00, 85.00, 'active', '2024-03-01', 'Ειδικός σε ελαιοχρώματα', 180.00, 2160.00);
INSERT INTO workers (name, phone, specialty, hourly_rate, daily_rate, status, hire_date, notes, total_hours, total_earnings) VALUES ('Σωτήρης Μιχαήλ', '6945333444', 'Ειδικός σε Ξύλο', 18.00, 120.00, 'active', '2023-06-10', 'Ειδικότητα σε ξύλινες επιφάνειες και επίπλα', 256.00, 4608.00);
INSERT INTO workers (name, phone, specialty, hourly_rate, daily_rate, status, hire_date, notes, total_hours, total_earnings) VALUES ('Κώστας Λάμπρου', '6956444555', 'Βοηθός Βαφέα', 10.00, 70.00, 'active', '2025-05-20', 'Νέος εργάτης σε εκπαίδευση', 45.00, 450.00);
INSERT INTO workers (name, phone, specialty, hourly_rate, daily_rate, status, hire_date, notes, total_hours, total_earnings) VALUES ('Παναγιώτης Νικολάου', '6967555666', 'Βαφέας', 14.00, 95.00, 'inactive', '2023-12-01', 'Προσωρινά μη διαθέσιμος - προσωπικοί λόγοι', 890.00, 12460.00);

-- MATERIALS
INSERT INTO materials (name, unit, unit_price, stock, min_stock, category) VALUES ('Πλαστικό Χρώμα Λευκό 3L', 'τμχ', 12.50, 50.00, 10.00, 'Χρώματα');
INSERT INTO materials (name, unit, unit_price, stock, min_stock, category) VALUES ('Πλαστικό Χρώμα Μπεζ 3L', 'τμχ', 13.00, 30.00, 10.00, 'Χρώματα');
INSERT INTO materials (name, unit, unit_price, stock, min_stock, category) VALUES ('Πλαστικό Χρώμα Γκρι 3L', 'τμχ', 13.00, 25.00, 8.00, 'Χρώματα');
INSERT INTO materials (name, unit, unit_price, stock, min_stock, category) VALUES ('Ελαιόχρωμα Λευκό 750ml', 'τμχ', 8.50, 25.00, 5.00, 'Χρώματα');
INSERT INTO materials (name, unit, unit_price, stock, min_stock, category) VALUES ('Ελαιόχρωμα Μπεζ 750ml', 'τμχ', 8.50, 15.00, 5.00, 'Χρώματα');
INSERT INTO materials (name, unit, unit_price, stock, min_stock, category) VALUES ('Ακρυλικό Χρώμα Μπλε 1L', 'τμχ', 9.00, 20.00, 5.00, 'Χρώματα');
INSERT INTO materials (name, unit, unit_price, stock, min_stock, category) VALUES ('Ακρυλικό Χρώμα Πράσινο 1L', 'τμχ', 9.00, 18.00, 5.00, 'Χρώματα');
INSERT INTO materials (name, unit, unit_price, stock, min_stock, category) VALUES ('Αστάρι Ακρυλικό 3L', 'τμχ', 11.00, 35.00, 8.00, 'Χρώματα');
INSERT INTO materials (name, unit, unit_price, stock, min_stock, category) VALUES ('Αστάρι Νερού 3L', 'τμχ', 10.50, 28.00, 8.00, 'Χρώματα');
INSERT INTO materials (name, unit, unit_price, stock, min_stock, category) VALUES ('Ρολό 25cm Πολυαμιδίου', 'τμχ', 3.50, 100.00, 20.00, 'Εργαλεία');
INSERT INTO materials (name, unit, unit_price, stock, min_stock, category) VALUES ('Ρολό 18cm Μικρό', 'τμχ', 2.80, 80.00, 15.00, 'Εργαλεία');
INSERT INTO materials (name, unit, unit_price, stock, min_stock, category) VALUES ('Πινέλο 5cm Επαγγελματικό', 'τμχ', 2.80, 80.00, 15.00, 'Εργαλεία');
INSERT INTO materials (name, unit, unit_price, stock, min_stock, category) VALUES ('Πινέλο 8cm Ραδιατέρ', 'τμχ', 3.20, 60.00, 12.00, 'Εργαλεία');
INSERT INTO materials (name, unit, unit_price, stock, min_stock, category) VALUES ('Σύστρα Μεταλλική 30cm', 'τμχ', 4.50, 40.00, 10.00, 'Εργαλεία');
INSERT INTO materials (name, unit, unit_price, stock, min_stock, category) VALUES ('Σύστρα Πλαστική 25cm', 'τμχ', 3.20, 50.00, 12.00, 'Εργαλεία');
INSERT INTO materials (name, unit, unit_price, stock, min_stock, category) VALUES ('Νάιλον Προστασίας 4x5m', 'τμχ', 1.50, 200.00, 50.00, 'Αναλώσιμα');
INSERT INTO materials (name, unit, unit_price, stock, min_stock, category) VALUES ('Ταινία Χαρτοταινία 50mm', 'τμχ', 2.20, 150.00, 30.00, 'Αναλώσιμα');
INSERT INTO materials (name, unit, unit_price, stock, min_stock, category) VALUES ('Σπατουλάρισμα 5kg', 'τμχ', 6.80, 45.00, 10.00, 'Χρώματα');
INSERT INTO materials (name, unit, unit_price, stock, min_stock, category) VALUES ('Διαλυτικό 1L', 'τμχ', 4.50, 30.00, 8.00, 'Αναλώσιμα');
INSERT INTO materials (name, unit, unit_price, stock, min_stock, category) VALUES ('Λούστρο Ματ 750ml', 'τμχ', 7.20, 22.00, 6.00, 'Χρώματα');

-- JOBS (όλες οι καταστάσεις)
INSERT INTO jobs (client_id, title, type, date, next_visit, description, address, city, postal_code, rooms, area, substrate, materials_cost, kilometers, billing_hours, billing_rate, vat, cost_per_km, notes, assigned_workers, paints, start_date, end_date, status, total_cost, is_paid, coordinates) VALUES (1, 'Βαφή Διαμερίσματος 2άρι', 'Εσωτερικοί χώροι', '2025-11-01', NULL, 'Πλήρης βαφή 2άρι διαμέρισμα με πλαστικό χρώμα σε όλους τους χώρους', 'Δημοκρατίας 45', 'Αλεξανδρούπολη', '68100', 2, 80.00, 'Γυψοσανίδα', 150.00, 5.00, 8.00, 50.00, 24.00, 0.50, 'Πελάτης πολύ ικανοποιημένος. Ζήτησε κάρτα για μελλοντικές εργασίες.', '[{\"workerId\":1,\"workerName\":\"Δημήτρης Βασιλείου\",\"workerSpecialty\":\"Βαφέας Senior\",\"hoursAllocated\":8,\"hourlyRate\":15,\"laborCost\":120}]', '[{\"name\":\"Λευκό Ματ\",\"code\":\"WH-001\",\"brand\":\"Vitex\"}]', '2025-11-01', '2025-11-05', 'Ολοκληρώθηκε', 1200.00, 1, '{\"lat\": 40.8476, \"lng\": 25.8759}');
INSERT INTO jobs (client_id, title, type, date, next_visit, description, address, city, postal_code, rooms, area, substrate, materials_cost, kilometers, billing_hours, billing_rate, vat, cost_per_km, notes, assigned_workers, paints, start_date, end_date, status, total_cost, is_paid, coordinates) VALUES (2, 'Βαφή Καταστήματος', 'Εσωτερικοί χώροι', '2025-11-10', '2025-11-18', 'Εσωτερική και εξωτερική βαφή καταστήματος ρούχων. Απαιτείται νυχτερινή εργασία.', '14ης Μαΐου 15', 'Αλεξανδρούπολη', '68100', 4, 150.00, 'Σοβάς', 350.00, 8.00, 16.00, 55.00, 24.00, 0.50, 'Εργασία σε εξέλιξη - 60% ολοκλήρωση. Πελάτης ζητά επιπλέον χρώμα στην είσοδο.', '[{\"workerId\":1,\"workerName\":\"Δημήτρης Βασιλείου\",\"workerSpecialty\":\"Βαφέας Senior\",\"hoursAllocated\":12,\"hourlyRate\":15,\"laborCost\":180},{\"workerId\":2,\"workerName\":\"Γιώργος Αντωνίου\",\"workerSpecialty\":\"Ελαιοχρωματιστής\",\"hoursAllocated\":12,\"hourlyRate\":12,\"laborCost\":144}]', '[{\"name\":\"Μπεζ Ανοιχτό\",\"code\":\"BG-002\",\"brand\":\"Vitex\"},{\"name\":\"Γκρι Σκούρο\",\"code\":\"GR-005\",\"brand\":\"Kraft\"}]', '2025-11-10', '2025-11-20', 'Σε εξέλιξη', 2800.00, 0, '{\"lat\": 40.8480, \"lng\": 25.8765}');
INSERT INTO jobs (client_id, title, type, date, next_visit, description, address, city, postal_code, rooms, area, substrate, materials_cost, kilometers, billing_hours, billing_rate, vat, cost_per_km, notes, assigned_workers, paints, start_date, end_date, status, total_cost, is_paid, coordinates) VALUES (3, 'Βαφή Γραφείου', 'Εσωτερικοί χώροι', '2025-11-20', NULL, 'Βαφή 3 χώρων γραφείου λογιστικής εταιρείας. Περιμένουμε έγκριση προσφοράς.', 'Κύπρου 42', 'Αλεξανδρούπολη', '68100', 3, 60.00, 'Γυψοσανίδα', 120.00, 3.00, 6.00, 50.00, 24.00, 0.50, 'Στάλθηκε προσφορά στις 10/11. Αναμένεται απάντηση έως 20/11.', '[]', '[{\"name\":\"Λευκό Ματ\",\"code\":\"WH-001\",\"brand\":\"Vitex\"}]', '2025-11-20', '2025-11-22', 'Υποψήφιος', 850.00, 0, '{\"lat\": 40.8470, \"lng\": 25.8750}');
INSERT INTO jobs (client_id, title, type, date, next_visit, description, address, city, postal_code, rooms, area, substrate, materials_cost, kilometers, billing_hours, billing_rate, vat, cost_per_km, notes, assigned_workers, paints, start_date, end_date, status, total_cost, is_paid, coordinates) VALUES (4, 'Εξωτερική Βαφή Μονοκατοικίας', 'Εξωτερικοί χώροι', '2025-12-01', NULL, 'Εξωτερική βαφή μονοκατοικίας 120τμ με ελαιόχρωμα. Απαιτείται ικριωματική.', 'Βενιζέλου 18', 'Αλεξανδρούπολη', '68100', 5, 250.00, 'Σοβάς', 600.00, 12.00, 24.00, 60.00, 24.00, 0.50, 'Μεγάλη εργασία - έχει επιβεβαιωθεί. Ξεκινάμε 1η Δεκεμβρίου. Χρειάζεται ικριωματική.', '[{\"workerId\":3,\"workerName\":\"Σωτήρης Μιχαήλ\",\"workerSpecialty\":\"Ειδικός σε Ξύλο\",\"hoursAllocated\":20,\"hourlyRate\":18,\"laborCost\":360},{\"workerId\":1,\"workerName\":\"Δημήτρης Βασιλείου\",\"workerSpecialty\":\"Βαφέας Senior\",\"hoursAllocated\":20,\"hourlyRate\":15,\"laborCost\":300}]', '[{\"name\":\"Ελαιόχρωμα Λευκό\",\"code\":\"OL-001\",\"brand\":\"Kraft\"},{\"name\":\"Ελαιόχρωμα Μπεζ\",\"code\":\"OL-002\",\"brand\":\"Kraft\"}]', '2025-12-01', '2025-12-10', 'Προγραμματισμένη', 3800.00, 0, '{\"lat\": 40.8490, \"lng\": 25.8770}');
INSERT INTO jobs (client_id, title, type, date, next_visit, description, address, city, postal_code, rooms, area, substrate, materials_cost, kilometers, billing_hours, billing_rate, vat, cost_per_km, notes, assigned_workers, paints, start_date, end_date, status, total_cost, is_paid, coordinates) VALUES (5, 'Βαφή Αποθήκης', 'Εσωτερικοί χώροι', '2025-10-15', NULL, 'Βαφή βιομηχανικής αποθήκης. Ακυρώθηκε από τον πελάτη.', 'Καραολή και Δημητρίου 33', 'Αλεξανδρούπολη', '68100', 1, 180.00, 'Τσιμέντο', 450.00, 15.00, 20.00, 45.00, 24.00, 0.50, 'Ακυρώθηκε - Πελάτης αποφάσισε να κάνει ανακαίνιση αργότερα. Δεν χρεώθηκε.', '[]', '[]', '2025-10-15', '2025-10-18', 'Ακυρώθηκε', 1350.00, 0, '{\"lat\": 40.8465, \"lng\": 25.8755}');
INSERT INTO jobs (client_id, title, type, date, next_visit, description, address, city, postal_code, rooms, area, substrate, materials_cost, kilometers, billing_hours, billing_rate, vat, cost_per_km, notes, assigned_workers, paints, start_date, end_date, status, total_cost, is_paid, coordinates) VALUES (6, 'Βαφή Εστιατορίου', 'Εσωτερικοί χώροι', '2025-11-25', '2025-12-15', 'Βαφή εστιατορίου με ειδικά χρώματα. Αναβλήθηκε λόγω καθυστέρησης παράδοσης υλικών.', 'Ελευθερίας 77', 'Αλεξανδρούπολη', '68100', 3, 100.00, 'Γυψοσανίδα', 280.00, 6.00, 12.00, 55.00, 24.00, 0.50, 'Αναβλήθηκε - Τα ειδικά χρώματα που ζήτησε ο πελάτης καθυστερούν. Νέα ημερομηνία: 15/12.', '[{\"workerId\":2,\"workerName\":\"Γιώργος Αντωνίου\",\"workerSpecialty\":\"Ελαιοχρωματιστής\",\"hoursAllocated\":10,\"hourlyRate\":12,\"laborCost\":120}]', '[{\"name\":\"Ακρυλικό Μπλε\",\"code\":\"AC-003\",\"brand\":\"Dulux\"},{\"name\":\"Ακρυλικό Πράσινο\",\"code\":\"AC-004\",\"brand\":\"Dulux\"}]', '2025-11-25', '2025-11-28', 'Αναβλήθηκε', 1850.00, 0, '{\"lat\": 40.8475, \"lng\": 25.8760}');
INSERT INTO jobs (client_id, title, type, date, next_visit, description, address, city, postal_code, rooms, area, substrate, materials_cost, kilometers, billing_hours, billing_rate, vat, cost_per_km, notes, assigned_workers, paints, start_date, end_date, status, total_cost, is_paid, coordinates) VALUES (7, 'Βαφή Μπαλκονιών', 'Κέγκελα/Πέργκολα', '2025-11-28', NULL, 'Βαφή μεταλλικών κέγκελων σε πολυκατοικία. Περιμένουμε καλοκαιρινές συνθήκες.', 'Αγίου Δημητρίου 9', 'Αλεξανδρούπολη', '68100', NULL, 0.00, 'Μέταλλο', 180.00, 4.00, 8.00, 50.00, 24.00, 0.50, 'Σε αναμονή καιρικών συνθηκών. Χρειάζεται 3 συνεχόμενες μέρες χωρίς βροχή.', '[{\"workerId\":2,\"workerName\":\"Γιώργος Αντωνίου\",\"workerSpecialty\":\"Ελαιοχρωματιστής\",\"hoursAllocated\":8,\"hourlyRate\":12,\"laborCost\":96}]', '[{\"name\":\"Ελαιόχρωμα Λευκό\",\"code\":\"OL-001\",\"brand\":\"Kraft\"}]', '2025-11-28', NULL, 'Σε αναμονή', 680.00, 0, '{\"lat\": 40.8478, \"lng\": 25.8762}');
INSERT INTO jobs (client_id, title, type, date, next_visit, description, address, city, postal_code, rooms, area, substrate, materials_cost, kilometers, billing_hours, billing_rate, vat, cost_per_km, notes, assigned_workers, paints, start_date, end_date, status, total_cost, is_paid, coordinates) VALUES (8, 'Βαφή Παιδικού Δωματίου', 'Εσωτερικοί χώροι', '2025-11-08', NULL, 'Βαφή παιδικού δωματίου με ειδικά χρώματα και σχέδια.', 'Σωκράτους 12', 'Αλεξανδρούπολη', '68100', 1, 25.00, 'Γυψοσανίδα', 95.00, 2.00, 4.00, 50.00, 24.00, 0.50, 'Πελάτης πολύ ευχαριστημένος με το αποτέλεσμα. Θα μας προτείνει.', '[{\"workerId\":1,\"workerName\":\"Δημήτρης Βασιλείου\",\"workerSpecialty\":\"Βαφέας Senior\",\"hoursAllocated\":4,\"hourlyRate\":15,\"laborCost\":60}]', '[{\"name\":\"Ακρυλικό Μπλε\",\"code\":\"AC-003\",\"brand\":\"Dulux\"},{\"name\":\"Λευκό Ματ\",\"code\":\"WH-001\",\"brand\":\"Vitex\"}]', '2025-11-08', '2025-11-09', 'Ολοκληρώθηκε', 495.00, 1, '{\"lat\": 40.8472, \"lng\": 25.8758}');
INSERT INTO jobs (client_id, title, type, date, next_visit, description, address, city, postal_code, rooms, area, substrate, materials_cost, kilometers, billing_hours, billing_rate, vat, cost_per_km, notes, assigned_workers, paints, start_date, end_date, status, total_cost, is_paid, coordinates) VALUES (9, 'Βαφή Καφετέριας', 'Εσωτερικοί χώροι', '2025-12-05', NULL, 'Ανακαίνιση καφετέριας - βαφή τοίχων και οροφής.', 'Καποδιστρίου 22', 'Αλεξανδρούπολη', '68100', 2, 85.00, 'Γυψοσανίδα', 220.00, 5.00, 10.00, 55.00, 24.00, 0.50, 'Προγραμματισμένη για αρχές Δεκεμβρίου. Πελάτης ζητά νυχτερινή εργασία.', '[{\"workerId\":4,\"workerName\":\"Κώστας Λάμπρου\",\"workerSpecialty\":\"Βοηθός Βαφέα\",\"hoursAllocated\":10,\"hourlyRate\":10,\"laborCost\":100}]', '[{\"name\":\"Γκρι Σκούρο\",\"code\":\"GR-005\",\"brand\":\"Kraft\"},{\"name\":\"Λευκό Ματ\",\"code\":\"WH-001\",\"brand\":\"Vitex\"}]', '2025-12-05', '2025-12-07', 'Προγραμματισμένη', 1420.00, 0, '{\"lat\": 40.8468, \"lng\": 25.8752}');
INSERT INTO jobs (client_id, title, type, date, next_visit, description, address, city, postal_code, rooms, area, substrate, materials_cost, kilometers, billing_hours, billing_rate, vat, cost_per_km, notes, assigned_workers, paints, start_date, end_date, status, total_cost, is_paid, coordinates) VALUES (10, 'Βαφή Σκάλας Πολυκατοικίας', 'Εσωτερικοί χώροι', '2025-11-15', NULL, 'Βαφή κλιμακοστασίου 4όροφης πολυκατοικίας.', 'Ορφέως 5', 'Αλεξανδρούπολη', '68100', NULL, 120.00, 'Σοβάς', 165.00, 3.00, 8.00, 48.00, 24.00, 0.50, 'Σε εξέλιξη - 40% ολοκλήρωση. 2 όροφοι ολοκληρώθηκαν.', '[{\"workerId\":1,\"workerName\":\"Δημήτρης Βασιλείου\",\"workerSpecialty\":\"Βαφέας Senior\",\"hoursAllocated\":6,\"hourlyRate\":15,\"laborCost\":90},{\"workerId\":4,\"workerName\":\"Κώστας Λάμπρου\",\"workerSpecialty\":\"Βοηθός Βαφέα\",\"hoursAllocated\":6,\"hourlyRate\":10,\"laborCost\":60}]', '[{\"name\":\"Μπεζ Ανοιχτό\",\"code\":\"BG-002\",\"brand\":\"Vitex\"}]', '2025-11-15', '2025-11-18', 'Σε εξέλιξη', 920.00, 0, '{\"lat\": 40.8482, \"lng\": 25.8768}');

-- CALENDAR EVENTS
INSERT INTO calendar_events (title, start_date, end_date, start_time, end_time, all_day, client_id, job_id, address, description, status, color, reminder_sent) VALUES ('Γιάννης Παπαδόπουλος - Βαφή Διαμερίσματος 2άρι', '2025-11-01 00:00:00', '2025-11-05 00:00:00', '09:00:00', '17:00:00', 0, 1, 1, 'Δημοκρατίας 45', 'Πλήρης βαφή 2άρι διαμέρισμα με πλαστικό χρώμα', 'completed', '#22c55e', 0);
INSERT INTO calendar_events (title, start_date, end_date, start_time, end_time, all_day, client_id, job_id, address, description, status, color, reminder_sent) VALUES ('Μαρία Νικολάου - Βαφή Καταστήματος', '2025-11-10 00:00:00', '2025-11-20 00:00:00', '08:00:00', '16:00:00', 0, 2, 2, '14ης Μαΐου 15', 'Εσωτερική και εξωτερική βαφή καταστήματος', 'in_progress', '#3b82f6', 0);
INSERT INTO calendar_events (title, start_date, end_date, start_time, end_time, all_day, client_id, job_id, address, description, status, color, reminder_sent) VALUES ('Ελένη Αθανασίου - Εξωτερική Βαφή Μονοκατοικίας', '2025-12-01 00:00:00', '2025-12-10 00:00:00', NULL, NULL, 1, 4, 4, 'Βενιζέλου 18', 'Εξωτερική βαφή μονοκατοικίας με ελαιόχρωμα', 'pending', '#f59e0b', 0);
INSERT INTO calendar_events (title, start_date, end_date, start_time, end_time, all_day, client_id, job_id, address, description, status, color, reminder_sent) VALUES ('Athanasios Zisoglou - Βαφή Μπαλκονιών', '2025-11-28 00:00:00', '2025-11-28 00:00:00', '10:00:00', '14:00:00', 0, 7, 7, 'Αγίου Δημητρίου 9', 'Βαφή μεταλλικών κέγκελων - Αναμονή καιρού', 'pending', '#6b7280', 0);
INSERT INTO calendar_events (title, start_date, end_date, start_time, end_time, all_day, client_id, job_id, address, description, status, color, reminder_sent) VALUES ('Ανδρέας Παύλου - Βαφή Καφετέριας', '2025-12-05 00:00:00', '2025-12-07 00:00:00', '22:00:00', '06:00:00', 0, 8, 9, 'Καποδιστρίου 22', 'Νυχτερινή εργασία - Ανακαίνιση καφετέριας', 'confirmed', '#8b5cf6', 0);
INSERT INTO calendar_events (title, start_date, end_date, start_time, end_time, all_day, client_id, job_id, address, description, status, color, reminder_sent) VALUES ('Σύσκεψη Εργασιών Εβδομάδας', '2025-11-14 00:00:00', '2025-11-14 00:00:00', '09:00:00', '10:00:00', 0, NULL, NULL, 'Γραφείο', 'Εβδομαδιαία σύσκεψη για προγραμματισμό εργασιών', 'confirmed', '#ec4899', 0);
INSERT INTO calendar_events (title, start_date, end_date, start_time, end_time, all_day, client_id, job_id, address, description, status, color, reminder_sent) VALUES ('Προμήθεια Υλικών', '2025-11-16 00:00:00', '2025-11-16 00:00:00', '11:00:00', '12:00:00', 0, NULL, NULL, 'Κατάστημα Χρωμάτων', 'Παραλαβή παραγγελίας χρωμάτων', 'pending', '#06b6d4', 0);
INSERT INTO calendar_events (title, start_date, end_date, start_time, end_time, all_day, client_id, job_id, address, description, status, color, reminder_sent) VALUES ('Επίσκεψη Πελάτη - Προσφορά', '2025-11-22 00:00:00', '2025-11-22 00:00:00', '15:00:00', '16:00:00', 0, 3, NULL, 'Κύπρου 42', 'Συζήτηση προσφοράς για βαφή γραφείου', 'confirmed', '#14b8a6', 0);

-- TEMPLATES
INSERT INTO templates (name, category, description, estimated_duration, materials, tasks) VALUES ('Βαφή Διαμερίσματος Στάνταρ', 'Εσωτερικοί χώροι', 'Τυπική βαφή διαμερίσματος με πλαστικό χρώμα', 16, '[{\"materialId\":1,\"materialName\":\"Πλαστικό Χρώμα Λευκό 3L\",\"quantity\":3,\"unitPrice\":12.50},{\"materialId\":4,\"materialName\":\"Ρολό 25cm\",\"quantity\":2,\"unitPrice\":3.50}]', '[{\"title\":\"Προετοιμασία χώρου\",\"duration\":2},{\"title\":\"Αστάρωμα\",\"duration\":4},{\"title\":\"Πρώτο χέρι\",\"duration\":6},{\"title\":\"Δεύτερο χέρι\",\"duration\":4}]');
INSERT INTO templates (name, category, description, estimated_duration, materials, tasks) VALUES ('Εξωτερική Βαφή Μονοκατοικίας', 'Εξωτερικοί χώροι', 'Εξωτερική βαφή με ελαιόχρωμα', 32, '[{\"materialId\":4,\"materialName\":\"Ελαιόχρωμα Λευκό 750ml\",\"quantity\":15,\"unitPrice\":8.50},{\"materialId\":9,\"materialName\":\"Σύστρα Μεταλλική\",\"quantity\":3,\"unitPrice\":4.50}]', '[{\"title\":\"Καθαρισμός επιφάνειας\",\"duration\":4},{\"title\":\"Ξύσιμο παλαιών χρωμάτων\",\"duration\":8},{\"title\":\"Αστάρωμα\",\"duration\":8},{\"title\":\"Πρώτο χέρι\",\"duration\":8},{\"title\":\"Δεύτερο χέρι\",\"duration\":4}]');
INSERT INTO templates (name, category, description, estimated_duration, materials, tasks) VALUES ('Βαφή Κέγκελων', 'Κέγκελα/Πέργκολα', 'Βαφή μεταλλικών κέγκελων με ελαιόχρωμα', 8, '[{\"materialId\":4,\"materialName\":\"Ελαιόχρωμα Λευκό 750ml\",\"quantity\":4,\"unitPrice\":8.50},{\"materialId\":5,\"materialName\":\"Πινέλο 5cm\",\"quantity\":3,\"unitPrice\":2.80}]', '[{\"title\":\"Καθαρισμός σκουριάς\",\"duration\":2},{\"title\":\"Αντισκωριακή προστασία\",\"duration\":2},{\"title\":\"Βαφή\",\"duration\":4}]');

-- OFFERS
INSERT INTO offers (client_id, offer_number, date, valid_until, items, subtotal, tax, discount, total, status, notes) VALUES (3, 'OFF-2025-001', '2025-11-10', '2025-12-10', '[{\"description\":\"Βαφή γραφείου - 3 χώροι\",\"quantity\":60,\"unit\":\"τμ\",\"unitPrice\":10.00,\"total\":600.00},{\"description\":\"Υλικά (χρώματα, ρολά)\",\"quantity\":1,\"unit\":\"σετ\",\"unitPrice\":120.00,\"total\":120.00}]', 720.00, 172.80, 0.00, 892.80, 'pending', 'Προσφορά για βαφή γραφείου. Ισχύει για 1 μήνα.');
INSERT INTO offers (client_id, offer_number, date, valid_until, items, subtotal, tax, discount, total, status, notes) VALUES (5, 'OFF-2025-002', '2025-10-15', '2025-11-15', '[{\"description\":\"Βαφή αποθήκης\",\"quantity\":180,\"unit\":\"τμ\",\"unitPrice\":8.00,\"total\":1440.00}]', 1440.00, 345.60, 50.00, 1735.60, 'rejected', 'Πελάτης απέρριψε την προσφορά - πολύ υψηλή τιμή κατά τη γνώμη του.');
INSERT INTO offers (client_id, offer_number, date, valid_until, items, subtotal, tax, discount, total, status, notes) VALUES (8, 'OFF-2025-003', '2025-12-01', '2026-01-01', '[{\"description\":\"Βαφή εμπορικού χώρου\",\"quantity\":85,\"unit\":\"τμ\",\"unitPrice\":12.00,\"total\":1020.00},{\"description\":\"Ειδικά χρώματα\",\"quantity\":1,\"unit\":\"σετ\",\"unitPrice\":280.00,\"total\":280.00}]', 1300.00, 312.00, 65.00, 1547.00, 'accepted', 'Προσφορά εγκρίθηκε. Ξεκινάμε 5 Δεκεμβρίου.');

-- SETTINGS
INSERT INTO settings (setting_key, setting_value, description) VALUES ('company_name', 'Οργανωτής Βαφέα Pro', 'Όνομα επιχείρησης');
INSERT INTO settings (setting_key, setting_value, description) VALUES ('company_address', 'Αλεξανδρούπολη', 'Διεύθυνση επιχείρησης');
INSERT INTO settings (setting_key, setting_value, description) VALUES ('company_phone', '6978799299', 'Τηλέφωνο επιχείρησης');
INSERT INTO settings (setting_key, setting_value, description) VALUES ('company_email', 'info@organotis-vafea.gr', 'Email επιχείρησης');
INSERT INTO settings (setting_key, setting_value, description) VALUES ('default_vat', '24', 'Προεπιλεγμένος ΦΠΑ %');
INSERT INTO settings (setting_key, setting_value, description) VALUES ('default_billing_rate', '50', 'Προεπιλεγμένη τιμή ώρας (€)');
INSERT INTO settings (setting_key, setting_value, description) VALUES ('currency', 'EUR', 'Νόμισμα');

SET FOREIGN_KEY_CHECKS = 1;

-- Τέλος αρχείου
